# Description: Configuration file for the experiment

# Data parameters
save_path: '/data/csalcedo/psrl/data'

# Environment and agent parameters
env: tworoom
agent: ucrl2
gamma: 0.99
no_goal: True

# Data generation parameters
training_steps: 1000000

# Transformer training parameters
epochs: 1
batch_size: 128
lr: 0.001
seq_len: 32