# Description: Configuration file for the experiment

# Setup parameters
seed: 2

# Environment and agent parameters
env: tworoom
agent: ucrl2
gamma: 0.99
no_goal: True

# Data generation parameters
training_steps: 100

# Transformer training parameters
epochs: 2
batch_size: 64
lr: 0.001
seq_len: 32

# Options
num_options: 4