# Description: Configuration file for the experiment

# Setup parameters
seed: 0

# Environment and agent parameters
env: fourroom
gamma: 0.99
no_goal: False

# Data generation parameters
training_steps: 1000000

# Plot parameters
plot_steps: 1000000