# Description: Configuration file for the experiment

# Data parameters
save_path: 'data'
plots_path: 'plots'

# Setup parameters
seed: 0

# Environment and agent parameters
env: riverswim
gamma: 0.99
no_goal: False

# Data generation parameters
training_steps: 100000

# Plot parameters
plot_steps: 100000