# Description: Configuration file for the experiment

# Setup parameters
seed: 0

# Environment and agent parameters
env: tworoom
agent: ucrl2
gamma: 0.99
no_goal: True

# Data generation parameters
training_steps: 1000000

# Transformer training parameters
epochs: 500
batch_size: 100
lr: 0.001
seq_len: 64

# Options
num_options: 4